### ISSUE TITLE
org-node timing out before indexing / `Error running timer ‘el-job-old--poll’: (wrong-type-argument el-job-old nil)` and `el-job-old: Timed out, was busy for 30+ seconds: org-mem`

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/el-job#7]
for a few months (I think) now, I've been getting errors of the type `Error running timer ‘el-job-old--poll’: (wrong-type-argument el-job-old nil)` and `el-job-old: Timed out, was busy for 30+ seconds: org-mem` and incomplete indexing of org-node files, though it seems to eventually resolve.

but on a new machine, I can't get a proper org-node index. I keep seeing the `Error running timer ‘el-job-old--poll’: (wrong-type-argument el-job-old nil)` message. and if I manually run `org-mem-reset` it spins for a bit but when I try any org-node command it says "waiting for org-mem" and then after a bit comes up with a blank index.

If I look at `*el-job-old debug info*` I see a ~15000 line buffer with a bunch of my org-node files indexed in it.

If I try to run `(org-mem-all-entries)`, it returns `nil`.

Is there a way I can increase the el-job timeout? Or use the new el-job-ng? Or use async? Or?  Just not sure how to approach this.

Thanks!

**Comment by emacsomancer** [comment]
(with a \*Backtrace\*:

```elisp
Debugger entered--Lisp error: (wrong-type-argument el-job-old nil)
  el-job-old--poll(43 (#<killed buffer> #<killed buffer> #<killed buffer>))
  apply(el-job-old--poll (43 (#<killed buffer> #<killed buffer> #<killed buffer>)))
  timer-event-handler([t 26989 61450 685144 nil el-job-old--poll (43 (#<killed buffer> #<killed buffer> #<killed buffer>)) nil 508000 nil])
```
)

**Comment by meedstrom** [comment]
Hi! Very sorry I haven't replied, it's been a low period recently. Looking at it now.

> Is there a way I can increase the el-job timeout? 

Usually when it hangs that long, it is simply hung and would remain that way forever. But to try it, you could redefine `el-job-old--poll`, changing line 652 from

      (if (<= n 42)

to something like

      (if (<= n 80)

which increases the timeout from ~28s to ~100s.  (Nevermind the weird algorithm. If interested, you can calculate the timeout by `(last (-reductions '+ (--map (/ it 32.0) (-iterate '1+ 1 42))))`, changing that 42 to 80 or your desired value.)

EDIT: Oh, line 660 has to change too, it's a redundant failsafe.  From

    (run-with-timer 30 nil #'el-job-old--reap (current-buffer))

to

    (run-with-timer 100 nil #'el-job-old--reap (current-buffer))

**Comment by meedstrom** [comment]
I'm rewriting org-mem to use el-job-ng. Shouldn't take too long, about an hour.

> If I look at `*el-job-old debug info*` I see a ~15000 line buffer with a bunch of my org-node files indexed in it.

It sounds like the parser is at least working correctly, so that the issue is in el-job only. To verify, you could try directly calling this in a throwaway Emacs instance (throwaway because it also globally sets the variables in `org-mem-inject-vars`, which by default will mess with `file-name-handler-alist`):

    (setq result (org-mem-parser--parse-file "~/one-of-your-files.org"))

especially if you have any reason to suspect a specific file of causing issues. 

If it does not hit an error or hang forever, it's probably fine. (I do `(setq result ...)` to inspect the value of `result` when debugging but you don't need that, come to think of it)


EDIT:  TL;DR: To test the parser on all files:

```elisp
(benchmark-elapse
  (setq results
        (mapcar #'org-mem-parser--parse-file
                (org-mem--list-files-from-fs))))
```

**Comment by meedstrom** [comment]
OK, org-mem [dev branch](https://github.com/meedstrom/org-mem/tree/dev) is now using el-job-ng. 

It does not have that pesky `el-job-old--poll` etc, so let me know if it works or you get a different error!

@emacsomancer Do you still use Elpaca? Remember that `(use-package org-mem :ensure (:branch "dev"))` would not switch the branch for you if the repo has already been downloaded, you may need to jump into the repo and use Magit or `git fetch --all && git switch dev && git pull -f`.  Then `M-x elpaca-rebuild`...

**Comment by meedstrom** [comment]
Now on main branch.

**Comment by meedstrom** [comment]
Thanks to your prompt, I've refactored el-job a bunch - news on[ readme ](https://github.com/meedstrom/el-job/)

Since you asked last year about some performance stuff, you might be interested about a new wrapper `el-job-parallel-mapcar`.  I'm happy to finally have gotten there at least!

     (el-job-parallel-mapcar FN INPUTS &optional INJECT-VARS)

**Comment by emacsomancer** [comment]
This looks excellent! Sorry it's a been a bit of a low time for me as well, and have been slow in doing anything.

I wonder if the new el-job will avoid the errors. Is it now the default? Or do I need to configure something?

For `el-job-parallel-mapcar`, what would be places to use it?

**Comment by emacsomancer** [comment]
Hmm... now I'm getting different errors. 

(With `toggle-debug-on-error`:

```elisp
Debugger entered--Lisp error: (error "Output file descriptor of el-job-ng:org-mem:1 is closed")
  process-send-region(#<process el-job-ng:org-mem:1> 1 375680)
  el-job-ng-run(:id org-mem :inject-vars (($bracket-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)]\\(?:\\[\\([^z-a]+?\\)]\\)?]") ($plain-re . "\\<\\(?:\\(file\\|https?\\|id\\)\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\)*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\)*[])>]\\)*[])>]\\)\\)") ($merged-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)]\\(?:\\[\\([^z-a]+?\\)]\\)?]\\|\\<\\(?:\\(file\\|https?\\|id\\)\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\)*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\)*[])>]\\)*[])>]\\)\\)") ($inlinetask-min-level) ($nonheritable-tags "crypt") ($use-tag-inheritance . t) ($default-todo-re . "\\(?:CANCELLED\\|D\\(?:EFERRED\\|ONE\\)\\|STARTED\\|TODO\\|WAITING\\)") ($ignore-regions-regexps ("^[ \11]*:ROAM_REFS:" . "$") ("^[ \11]*:BACKLINKS:" . "$") ("^[ \11]*:BACKLINKS:[ \11]*$" . "^[ \11]*:END:[ \11]*$") ("^[ \11]*#\\+begin_src" . "^[ \11]*#\\+end_src") ("^[ \11]*#\\+begin_example" . "^[ \11]*#\\+end_example") ("^[ \11]*#\\+begin_comment" . "^[ \11]*#\\+end_comment") ("^[ \11]*#\\+transclude:" . "$")) (file-name-handler-alist)) :require (org-mem-parser) :eval nil :inputs ("/home/emacsomancer/Documents/Org/calendars/Opportunities.org" "/home/emacsomancer/Documents/Org/calendars/VPers.org" "/home/emacsomancer/Documents/Org/calendars/Teaching.org" "/home/emacsomancer/Documents/Org/calendars/Teaching.org_archive" "/home/emacsomancer/Documents/Org/calendars/Personal.org" "/home/emacsomancer/Documents/Org/calendars/Personal.org_archive" "/home/emacsomancer/Documents/Org/calendars/Helm.org" "/home/emacsomancer/Documents/Org/calendars/Lisp.org" "/home/emacsomancer/Documents/Org/calendars/Hols.org" "/home/emacsomancer/Documents/Org/calendars/Circus.org" "/home/emacsomancer/Documents/Org/calendars/CTSMDC.org" "/home/emacsomancer/Documents/Org/calendars/BdayAnn.org" "/home/emacsomancer/Documents/Org/calendars/Agenda.org" "/home/emacsomancer/Documents/Org/calendars/Agenda.org_archive" "/home/emacsomancer/Documents/Org/org-roam/daily/data/17/2283d1-d570-4901-b1ea-6946cfe25dfc/liar dilemma.org" "/home/emacsomancer/Documents/Org/org-roam/daily/data/6e/685725-207a-4fb4-8f93-d396794e156d/onlisp.org" "/home/emacsomancer/Documents/Org/org-roam/daily/data/55/86a8f7-3fc1-4173-ba75-1b45afcf9718/lecture_notes.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-22.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-21.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-15.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-13.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-09.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-08.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-05.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-04.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2024-12-30.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-06.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-03.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2026-01-01.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-31.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-25.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-24.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-23.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-22.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-20.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2022-08-11.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-03-06.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-16.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-15.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-14.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-11.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-10.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-09.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-08.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-07.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-06.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-04.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-11-30.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-12-03.org" "/home/emacsomancer/Documents/Org/org-roam/daily/2025-11-25.org" ...) :funcall-per-input org-mem-parser--parse-file :callback org-mem--finalize-full-scan)
  org-mem--scan-full(t nil)
  org-mem-reset(nil nil 1)
  funcall-interactively(org-mem-reset nil nil 1)
  call-interactively(org-mem-reset record nil)
  command-execute(org-mem-reset record)
  execute-extended-command(nil "org-mem-reset" "org mem")
  funcall-interactively(execute-extended-command nil "org-mem-reset" "org mem")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

In `*Messages*`:

```elisp
el-job-ng: Process exited abnormally with code 255
status:      exit
exit status: 255
buffer:      #<buffer  *el-job-ng:org-mem:0*>
el-job id:   org-mem
tip:         check the hidden buffer named (note leading space): " *el-job-ng:org-mem:err*"
Error running timer ‘org-mem--scan-full’: (error "Output file descriptor of el-job-ng:org-mem:1 is closed")
```

in ` *el-job-ng:org-mem:err*`:
```elisp
Wrong type argument: listp, native-comp-eln-load-path

Process el-job-ng:org-mem:1 stderr finished

Process el-job-ng:org-mem:0 stderr finished
```

(note on this [Chimera Linux] system I don't have `nativecomp`; I'll have to test on a different system to see if this makes a difference.)

in ` *el-job-ng:org-mem:0*`:
```elisp

Error: wrong-type-argument (listp native-comp-eln-load-path)
  car(native-comp-eln-load-path)
  el-job-ng--child-work()
  command-line-1(("--load" "/home/slade/.emacs.d/elpaca/builds/el-job/el-job-ng.elc" "--funcall" "el-job-ng--child-work"))
  command-line()
  normal-top-level()
```

` *el-job-ng:org-mem:1*` and  ` *el-job-ng:org-mem:2*`  lists a lot of my elpaca packages filepaths, and then a number of my org-roam\org-node files with full filepaths.

I don't know if any of this is helpful. I'll also have to try on a machine with Emacs with nativecomp available.

**Comment by emacsomancer** [comment]
Notes:

- tried it on a different machine (plain Guix System build of `emacs-pgtk` 30.2 with native-comp) that has native compilation available and I don't seem have any problems with it there ( ` *el-job-ng:org-mem:err*` there just says `Process el-job-ng:org-mem:0 stderr finish`)
- haven't yet tried on the other machine (a SecureBlue machine with `emacs-pgtk` 30.2 with native-comp, but also with whatever hardening Fedora does to Emacs, plus whatever SELinux policies apply) where I was having trouble with `el-job-old`, so I'll have to check that one yet.


but the Chimera no-nativecomp Emacs build suggests to me that native-comp being missing creates problems? (I don't know, there are those error messages complaining about native-comp anyway, though I haven't dug into source to see what's going on yet ....  though Chimera does other unusual things, like using musl, llvm/clang, and various toolchain harderning.... `system-configuration-options` reports:

```elisp
"--prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --libdir=/usr/lib 
--mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --build=x86_64-chimera-linux-musl 
--host=x86_64-chimera-linux-musl --with-gameuser=:_games --with-gpm --with-jpeg --with-json
 --with-pgtk --with-webp --with-x-toolkit=gtk3 --with-native-compilation--without-tiff
 'CFLAGS=-ffile-prefix-map=/builddir/emacs-pgtk-30.2=. 
-Wformat -Werror=format-security -ftrivial-auto-var-init=zero -fstack-clash-protection 
-fvisibility=hidden  -fno-omit-frame-pointer -fsanitize=signed-integer-overflow,integer-divide-by-zero 
-fsanitize-trap=signed-integer-overflow,integer-divide-by-zero -fno-sanitize-recover -flto=thin -O2 -g2' 
'LDFLAGS=-Wl,-z,pack-relative-relocs -Wl,-O2 
-fvisibility=hidden -fno-omit-frame-pointer -fsanitize=signed-integer-overflow,integer-divide-by-zero
 -fsanitize-trap=signed-integer-overflow,integer-divide-by-zero -fno-sanitize-recover -flto=thin'"
```
)

**Comment by meedstrom** [comment]
Ah, thanks, I assumed too much and didn't test how `el-job-ng-vars` would behave. Fixed in 2.7.1.

>  Is it now the default? Or do I need to configure something?

Default.

Hope your times get better!

**Comment by meedstrom** [comment]
A lot of machines you got there, bud. 😆 Do you have fun with them?

It's good for testing at least.

**Comment by emacsomancer** [comment]
> Ah, thanks, I assumed too much and didn't test how `el-job-ng-vars` would behave. Fixed in 2.7.1.

Thanks! The Chimera/no-native-comp seems to be working fine with 2.7.1. I'll check the other machine that was having issues tomorrow.  

> A lot of machines you got there, bud. 😆 Do you have fun with them?

A lot of old ThinkPads really. Yeah, useful to have a few different machines to try different things out on, while still having something working somewhere.

> Hope your times get better!

Cheers! I hope so. To better times!

**Comment by emacsomancer** [comment]
Checked the SecureBlue machine, and I'm happy to report that it is working now too (and Org-Node seemed completely broken on it prior).  🎉 

Thanks for the continued innovation here! (I'd had to fall back on plain old org-roam on this machine and the difference in performance & features between it & org-node was very salient.)

(Hoping to have a chance at some point to actually look again more at the code as it's been a while since I've spent time with it and you've made a lot of changes in-between.)
